---
docker_version: "*"
docker_compose_version: "1.25"

cloudflare_api_email: "{{ vault_cloudflare_api_email }}"
cloudflare_api_key: "{{ vault_cloudflare_api_key }}"

letsencrypt_email: "{{ vault_letsencrypt_email }}"

docker_users:
  - automation
  - nicolas

zion_user:
  uid: 1000
  gid: 1000
  name: nicolas
  shell: /bin/bash
  groups:
    - sudo
    - nicolas
    - users
 
zion_shell: /bin/bash
zion_authorized_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFHULTVEYcLyiNlaL2FqUvbBSGMcxXkZvVFGD2Dizp+H thiccpad for ZION"
