---
- name: Install unbound dns server package
  apt:
    pkg:
      - unbound
    state: present

- name: Copy unbound configuration files
  template:
    src: "{{ item }}"
    dest: "{{ unbound_conf.d }}/{{ item.replace('.j2', '') }}"
    mode: 0644
    owner: root
    group: root
    force: yes
  with_fileglob:
    - "unbound.conf.d/*"

- name: Copy unbound main configuration file
  template:
    src: unbound.conf.j2
    dest: "{{ unbound_conf }}/unbound.conf"
    mode: 0644
    owner: root
    group: root
    force: yes
    validate: /usr/sbin/unbound-checkconf -f %s

- name: Create unbound cache directory
  file:
    path: {{ unbound_cache }}
    state: directory
    owner: unbound
    group: unbound
    mode: 0755

- name: Create unbound dnssec directory
  file:
    path: {{ unbound_lib_conf }}
    state: directory
    owner: unbound
    group: unbound
    mode: 0755

- name: Register unbound logrotate configuration
  when: "'logrotate' in ansible_facts.packages"
  block:
    - name: Copy unbound logrotate configuration
      template:
        src: logrotate.conf.j2
        dest: "{{ unbound_conf }}/logrotate.conf"
        mode: 0644
        owner: root
        group: root
        force: yes
    - name: Validate unbound logrotate configuration
      become: yes
      become_user: root
      command: "/usr/sbin/logrotate -d {{ unbound_conf }}/logrotate.conf"
    - name: Load logrotate configuration
      become: yes
      become_user: root
      command: "/usr/sbin/logrotate {{ unbound_conf }}/logrotate.conf"
    - name: Reload logrotate
      systemd:
        name: logrotate
        state: reloaded

- name: Restart unbound dns
  systemd:
    name: unbound
    state: reloaded
