---
- name: reload traefik
  docker_service:
    project_name: traefik
    project_src: "{{ traefik_config_folder }}"
    state: present
    restarted: yes
    pull: yes
  vars:
    ansible_python_interpreter:  "{{ '/usr/bin/env python-docker' }}"
