---
- name: Install docker compose
  pip:
    name: docker-compose
    version: "{{ docker_compose_version }}"
    state: present
    executable: pip3

- name: Add Ansible user to Docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"
